# Generated by Django 5.2.6 on 2025-12-23 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='stream',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
