# Generated by Django 5.2.8 on 2026-02-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_subject_description_remove_subject_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(default='Grade 13', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.CharField(default='Combined Maths', max_length=50),
        ),
    ]
