# Generated by Django 5.2.6 on 2026-02-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_class_fee_subject_description_subject_grade_and_more'),
        ('users', '0008_remove_user_grades_list_alter_user_current_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.grade'),
        ),
    ]
