# Generated by Django 5.2.6 on 2026-02-26 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_subject_grade'),
        ('users', '0008_remove_user_grades_list_alter_user_current_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.grade'),
        ),
    ]
