# Generated by Django 5.2.6 on 2026-02-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_subject_grade'),
        ('users', '0008_remove_user_grades_list_alter_user_current_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.AddField(
            model_name='subject',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='users.grade'),
        ),
    ]
