# Generated by Django 5.2.6 on 2026-02-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('payment_pending', 'Payment Pending')], default='pending', max_length=20),
        ),
    ]
