# Generated by Django 5.2.6 on 2026-02-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('subjects', '0007_remove_subject_grade_subject_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='class_obj',
        ),
        migrations.AddField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
            preserve_default=False,
        ),
    ]
