# Generated by Django 5.2.6 on 2026-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_month_payment_year_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='cash', max_length=50),
        ),
    ]
