# Generated by Django 5.2.6 on 2026-02-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='grades_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='grades',
        ),
        migrations.AddField(
            model_name='user',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='users.grade'),
        ),
    ]
