# Generated by Django 5.2.6 on 2026-02-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_grade_user_grades_list_remove_user_grades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grades_list',
        ),
        migrations.AlterField(
            model_name='user',
            name='current_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.grade'),
        ),
    ]
