# Generated by Django 4.2 on 2026-05-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_teacherapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
