# Generated by Django 4.2 on 2026-05-23 02:30

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_admin_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    
    # Check if a superuser already exists
    if not User.objects.filter(is_superuser=True).exists():
        # Create a new default superuser
        User.objects.create(
            username='admin',
            email='admin@a9education.com',
            password=make_password('adminpassword123'),
            is_staff=True,
            is_superuser=True,
            role='teacher',
            name='Administrator'
        )

def remove_admin_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_teacherapplication_email'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_code=remove_admin_user),
    ]
